package com.example.clickbuy.models

data class Orders (
    val orders: List<Order>
)

data class Order (
    val id: Long,
    val admin_graphql_api_id: String,
    val app_id: Long,
    val browser_ip: Any? = null,
    val buyer_accepts_marketing: Boolean,
    val cancel_reason: Any? = null,
    val cancelled_at: Any? = null,
    val cart_token: Any? = null,
    val checkout_id: Any? = null,
    val checkout_token: Any? = null,
    val closed_at: Any? = null,
    val confirmed: Boolean,
    val contact_email: String,
    val created_at: String,
    val currency: String,
    val current_subtotal_price: String,
    val current_subtotal_priceSet: Set,
    val current_total_discounts: String,
    val current_total_discountsSet: Set,
    val current_total_duties_set: Any? = null,
    val current_total_price: String,
    val current_total_price_set: Set,
    val current_total_tax: String,
    val current_total_tax_set: Set,

    val customer_locale: Any? = null,
    val device_id: Any? = null,
    val discount_codes: List<Any?>,
    val email: String,
    val estimated_taxes: Boolean,
    val financial_status: String,
    val fulfillment_status: Any? = null,
    val gateway: String,
    val landing_site: Any? = null,
    val landing_site_ref: Any? = null,
    val location_id: Any? = null,
    val name: String,
    val note: String? = null,
    val note_attributes: List<Any?>,
    val number: Long,
    val order_number: Long,
    val order_status_url: String,
    val original_total_duties_set: Any? = null,
    val payment_gateway_names: List<Any?>,
    val phone: Any? = null,
    val presentment_currency: String,
    val processed_at: String,
    val processing_method: String,
    val reference: Any? = null,
    val referring_site: Any? = null,
    val source_identifier: Any? = null,
    val source_name: String,
    val source_url: Any? = null,
    val subtotal_price: String,
    val subtotal_price_set: Set,
    val tags: String,
    val tax_lines: List<Any?>,
    val taxes_included: Boolean,
    val test: Boolean,
    val token: String,
    val total_discounts: String,
    val total_discounts_set: Set,
    val total_line_items_price: String,
    val total_line_items_price_set: Set,
    val total_outstanding: String,
    val total_price: String,
    val total_price_set: Set,
    val total_price_usd: String,
    val total_shipping_price_set: Set,
    val total_tax: String,
    val total_tax_set: Set,
    val total_tip_received: String,
    val total_weight: Long,
    val updated_at: String,
    val user_id: Any? = null,
    val customer: Customer,
    val discount_applications: List<Any?>,
    val fulfillments: List<Any?>,
    val line_items: List<LineItem>,
    val payment_terms: Any? = null,
    val refunds: List<Any?>,
    val shipping_lines: List<Any?>,
    val billing_address: Address? = null,
    val shipping_address: Address? = null
)

data class Address (
    val first_name: String,
    val address1: String,
    val phone: String,
    val city: String,
    val zip: String,
    val province: String,
    val country: String,
    val last_name: String,
    val address2: Any? = null,
    val company: Any? = null,
    val latitude: Any? = null,
    val longitude: Any? = null,
    val name: String,
    val country_code: String,
    val province_code: Any? = null,
    val id: Long? = null,
    val customer_id: Long? = null,
    val country_name: String? = null,
    val default: Boolean? = null
)

data class Set (
    val shop_money: Money,
    val presentment_money: Money
)

data class Money (
    val amount: String,
    val currency_code: String
)

data class Customer (
    val id: Long,
    val email: String,
    val accepts_marketing: Boolean,
    val created_at: String,
    val updated_at: String,
    val first_name: String? = null,
    val last_name: String? = null,
    val orders_count: Long,
    val state: String,
    val total_spent: String,
    val last_order_id: Long,
    val note: String? = null,
    val verified_email: Boolean,
    val multipass_identifier: Any? = null,
    val tax_exempt: Boolean,
    val phone: String? = null,
    val tags: String,
    val last_order_name: String,
    val currency: String,
    val accepts_marketing_updated_at: String,
    val marketing_opt_in_level: Any? = null,
    val tax_exemptions: List<Any?>,
    val email_marketing_consent: MarketingConsent? = null,
    val sms_marketing_consent: MarketingConsent? = null,
    val admin_graphql_api_id: String,
    val default_address: Address? = null
)

data class MarketingConsent (
    val state: String,
    val opt_in_level: String,
    val consent_updated_at: Any? = null,
    val consent_collected_from: String? = null
)

data class LineItem (
    val id: Long,
    val admin_graphql_api_id: String,
    val fulfillable_quantity: Long,
    val fulfillment_service: String,
    val fulfillmentStatus: Any? = null,
    val gift_card: Boolean,
    val grams: Long,
    val name: String,
    val price: String,
    val price_set: Set,
    val product_exists: Boolean,
    val product_id: Long,
    val properties: List<Any?>,
    val quantity: Long,
    val requires_shipping: Boolean,
    val sku: String,
    val taxable: Boolean,
    val title: String,
    val total_discount: String,
    val total_discount_set: Set,
    val variant_id: Long,
    val variant_inventory_management: String,
    val variant_title: String,
    val vendor: String,
    val tax_lines: List<Any?>,
    val duties: List<Any?>,
    val discount_allocations: List<Any?>
)
